
name: Test JBang

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: jbang
        uses: jbangdev/setup-jbang@main  
      - name: env
        run: |
          jbang properties@jbangdev
  windows:
    runs-on: windows-latest
    steps:
      - name: jbang
        uses: jbangdev/setup-jbang@main  
      - name: env
        run: |
          jbang properties@jbangdev
  java21:
      runs-on: ubuntu-latest
      steps:
      - name: java 17
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: jbang
        uses: jbangdev/setup-jbang@main    
      - name: complexhelloworld
        run: |
          jbang properties@jbangdev java
        
        